### ISSUE TITLE
java version conflicted

### ISSUE THREAD

**Issue by venenos** [LibrePlan/libreplan#1863]
org.springframework.web.context.ContextLoader  - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [jar:file:/usr/share/apache-tomcat-7.0.41/webapps/libreplan/WEB-INF/lib/libreplan-business-1.4.1.jar!/libreplan-business-spring-config.xml]; nested exception is java.lang.IllegalStateException: AnnotationAwareAspectJAutoProxyCreator is only available on Java 1.5 and higher

We have a version jdk1.8.0_16 and the system is centos 6.

**Comment by grypho** [comment]
You are using the precompiled .war file, aren't you? There is a version detection bug in the spring framework which cannot detect jdk1.8 correctly. See https://stackoverflow.com/questions/33891697/annotationawareaspectjautoproxycreator-is-only-available-on-java-1-5-and-higher for details.

Solved that issue by compiling the .war file for myself from git sources.

**Comment by kwoot** [comment]
This problem only occurs in libreplan-1.4 branch. We are currently working on getting that at least to compile. Any help is highly appreciated.

**Comment by dseixas** [comment]
Hi, I've downloaded the latest available version of libreplan (i.e. 1.4.1) from https://sourceforge.net/projects/libreplan/files/LibrePlan/ and it still have the same problem.

@grypho will you be kind enough and share your war (if possible for mysql)? 

I've been trying to get the project up and running and it's a nightmare

Thanks in advance.

**Comment by grypho** [comment]
Hi @dseixas ,

I can share a mysql version (GitHub head) tomorrow morning when I have access to my dev machine.
Do you also need a .sql database file to set up the database correctly?

Carsten

**Comment by grypho** [comment]
Hi @dseixas ,

I put a mysql build online that you can download.

https://carsten.familie-schumann.info/libreplan-webapp-mysql-1ca2cb8.war

This .war reflects the most recent commit of the grypho/libreplan repository (which is in sync with libreplan/libreplan).

**Comment by dseixas** [comment]
Hi @grypho ,

You're a life saviour!!! Thanks so much for the quick answer. 

The SQL file would be also very helpful. 

Best regards

**Comment by grypho** [comment]
SQL file: https://carsten.familie-schumann.info/install-mysql-1ca2cb8.sql
I'm not sure if that works beacuse I had no time to test against a real database. Please tell me if it doesn't work...

**Comment by dseixas** [comment]
Thanks again... I'm having some issues trying to start the war.

Namely, I had to add the mysql driver and now I'm getting an
OutOfMemoryError...

**Comment by dseixas** [comment]
Sure thing,

Uname -a

Linux Gamification 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01
UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Free -h

              total        used        free      shared  buff/cache
available

Mem:           7.8G        5.4G        237M        369M        2.2G
1.7G

Swap:          4.0G        3.7G        270M

Tomcat version is 8.0.36


We have several apps in the same tomcat (actually quite a few) and I've
tried to remove some that are currently not being used but no change at all.

The error happens at starting the libreplan app.

This is the error log:

23-Oct-2019 12:23:23.875 INFO [main]
org.apache.catalina.startup.Catalina.start Server startup in 5108578 ms

23-Oct-2019 12:23:42.683 INFO [Statistics Thread-__DEFAULT__-1]
org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading
Illegal access: this web application instance has been stopped already.
Could not load [java.lang.OutOfMemoryError]. The following stack trace is
thrown for debugging purposes as well as to attempt to terminate the thread
which caused the illegal access.

 java.lang.IllegalStateException: Illegal access: this web application
instance has been stopped already. Could not load
[java.lang.OutOfMemoryError]. The following stack trace is thrown for
debugging purposes as well as to attempt to terminate the thread which
caused the illegal access.

at
org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1352)

at
org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1340)

at
org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1205)

at
org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)

at
net.sf.ehcache.util.concurrent.ConcurrentHashMap.values(ConcurrentHashMap.java:2722)

at
net.sf.ehcache.util.concurrent.ConcurrentHashMap.values(ConcurrentHashMap.java:220)

at
net.sf.ehcache.statistics.extended.ExtendedStatisticsImpl$1.run(ExtendedStatisticsImpl.java:104)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)

at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)

at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)

at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)




Casten thank so much!!!

**Comment by dseixas** [comment]
Hi Carsten,

I managed to almost get libreplan up and running (it took me a new server
and implement manually the database changes).

Now I'm facing the following issue: I don't have a LDAP to authenticate
users so how can I configure the server to use database users?

I believe is using the
WEB-INF/classes/libreplan-webapp-spring-security-config.xml file but, how?

Thanks in advance.

**Comment by grypho** [comment]
Hey, that sounds great.

As fas as I can remember, LDAP is only an option that is not default. I've two running instances that I use in production and I neither set up an LDAP server nor did configure anything to turn LDAP off. To my understanding you are using a database authentication by default unless you activate LDAP.

If you take a look into the configuration (after logging in with default credentials) [Configuration -> Main Configuration] you can see a deactivated LDAP option (sorry, currently only have a german screenshot). The first checkbox means "activate LDAP":
![grafik](https://user-images.githubusercontent.com/9314376/68644788-6af3bf80-0516-11ea-842a-5be1d388cc65.png)

Are you running into some type of LDAP related error message or why do you think you have to deactivate LDAP?


Carsten

**Comment by dseixas** [comment]
Hey Carsten,

First of all, thanks for your prompt response. Actually, after a 12h shift
I wasn't seen things straight... I had a database issue before the log-in
problem.

This morning came fresh and sorted it out.

Now, do you know or anyone else how can I share the updated war and sql so
anyone can use it?

Best regards
