### ISSUE TITLE
Unable to work in gantt view

### ISSUE THREAD

**Issue by kwoot** [LibrePlan/libreplan#1914]
After creating a project with 2 simple tasks, switching to gantt/schedule view it is unable to edit the planning.

Log:
127.0.0.1 -  -  [12/jul/2019:18:47:59 +0000] "POST /libreplan-webapp/zkau HTTP/1.1" 200 91 "http://127.0.0.1:8090/libreplan-webapp/planner/index.zul" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
ERROR [12-juli 20:48:00] [pool-5-thread-2] org.zkoss.ganttz.util.LongOperationFeedback  - unable to access desktop
org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.zk.ui.impl.PollingServerPush.activate(PollingServerPush.java:307)
	at org.zkoss.zk.ui.impl.DesktopImpl.activateServerPush(DesktopImpl.java:1412)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:971)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:947)
	at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR [12-juli 20:48:00] [pool-5-thread-4] org.zkoss.ganttz.util.LongOperationFeedback  - unable to access desktop
org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.zk.ui.impl.PollingServerPush.activate(PollingServerPush.java:307)
	at org.zkoss.zk.ui.impl.DesktopImpl.activateServerPush(DesktopImpl.java:1412)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:971)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:947)
	at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
ERROR [12-juli 20:48:00] [pool-5-thread-3] org.zkoss.ganttz.util.LongOperationFeedback  - error executing background operation
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.ganttz.util.LongOperationFeedback$8.waitUntilShowingAllUpdates(LongOperationFeedback.java:227)
	at org.zkoss.ganttz.util.LongOperationFeedback$8.doOperation(LongOperationFeedback.java:219)
	at org.zkoss.ganttz.util.LongOperationFeedback$7.run(LongOperationFeedback.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.zkoss.ganttz.util.LongOperationFeedback$8.waitUntilShowingAllUpdates(LongOperationFeedback.java:225)
	... 5 more
Caused by: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:276)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.zk.ui.impl.PollingServerPush.activate(PollingServerPush.java:307)
	at org.zkoss.zk.ui.impl.DesktopImpl.activateServerPush(DesktopImpl.java:1412)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:971)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:947)
	at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:273)
	... 5 more
ERROR [12-juli 20:48:00] [pool-5-thread-1] org.zkoss.ganttz.util.LongOperationFeedback  - error executing background operation
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.ganttz.util.LongOperationFeedback$8.waitUntilShowingAllUpdates(LongOperationFeedback.java:227)
	at org.zkoss.ganttz.util.LongOperationFeedback$8.doOperation(LongOperationFeedback.java:219)
	at org.zkoss.ganttz.util.LongOperationFeedback$7.run(LongOperationFeedback.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.zkoss.ganttz.util.LongOperationFeedback$8.waitUntilShowingAllUpdates(LongOperationFeedback.java:225)
	... 5 more
Caused by: java.lang.RuntimeException: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:276)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: org.zkoss.zk.ui.DesktopUnavailableException: Stopped
	at org.zkoss.zk.ui.impl.PollingServerPush.activate(PollingServerPush.java:307)
	at org.zkoss.zk.ui.impl.DesktopImpl.activateServerPush(DesktopImpl.java:1412)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:971)
	at org.zkoss.zk.ui.Executions.activate(Executions.java:947)
	at org.zkoss.ganttz.util.LongOperationFeedback$NotBlockingDesktopUpdates.run(LongOperationFeedback.java:273)
	... 5 more
127.0.0.1 -  -  [12/jul/2019:18:48:00 +0000] "GET /libreplan-webapp/planner/index.zul;order=ORDER0001 HTTP/1.1" 200 16020 "http://127.0.0.1:8090/libreplan-webapp/planner/index.zul" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"

**Comment by kwoot** [comment]
After some time browser firefox says script on page takes a lot of time. Looks like some endless loop.

**Comment by grypho** [comment]
Duplicate of #1908

**Comment by kwoot** [comment]
Stupid me.
